//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minwin
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int peer_id { get; set; }
        public bool status { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> sender_id { get; set; }
        public Nullable<int> receiver_id { get; set; }
        public string sender_message { get; set; }
        public string receiver_message { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
